# Generated by Django 6.0.5 on 2026-05-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_email_token_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='owner',
            field=models.CharField(default=1, max_length=35, unique=True, verbose_name='владелец'),
            preserve_default=False,
        ),
    ]
