# Generated by Django 6.0.5 on 2026-05-29 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='owner',
        ),
    ]
