# Generated by Django 6.0.5 on 2026-05-27 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'блог', 'verbose_name_plural': 'блоги'},
        ),
    ]
