# Generated by Django 6.0.4 on 2026-05-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='views_counter',
            field=models.PositiveIntegerField(default=0, help_text='укажите количество просмотров', verbose_name='счетчик просмотров'),
        ),
    ]
