# Generated by Django 6.0.5 on 2026-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='владелец продукта'),
        ),
    ]
