# Generated by Django 6.0.5 on 2026-05-29 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_product_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(default='yuzhakov.a.a@mail.ru', on_delete=django.db.models.deletion.CASCADE, related_name='владелец', to=settings.AUTH_USER_MODEL),
        ),
    ]
